### ISSUE TITLE
"errorType": "Runtime.UnmarshalError"

### ISSUE THREAD

**Issue by tvh8** [mukulmantosh/ServerlessDemo#1]
After running the code for the first Create Operation in the "Writing REST APIs Beginning CRUD (Create, Read, Update, Delete) Operations" section I receive the error message below. I cannot figure out where or why I am receiving the error.

{"errorMessage": "Unable to unmarshal input: Extra data: line 3 column 2 - line 3 column 3 (char 124 - 125)", "errorType": "Runtime.UnmarshalError", "requestId": "ee2a3cca-c249-4ae4-917e-1c29ecb7ff9a", "stackTrace": []}END RequestId: ee2a3cca-c249-4ae4-917e-1c29ecb7ff9a

**Comment by mukulmantosh** [comment]
Try passing data in this format:

```python3

{
  "body": "{\"first_name\": \"Mukul\", \"last_name\": \"Mukul\", \"email\": \"abc@gmail.com\", \"password\": \"securesecret123\"}"
}

```

Check image for reference : https://www.jetbrains.com/pycharm/guide/static/a2a28fe71670fd91b1229d1ee9081e5a/3f8aa/step8.png

**Comment by tvh8** [comment]
That worked, thank you!
